### PR TITLE
Animal Updates including Camel and Hyena

### LINKED ISSUE #1006: TFCT: Cat AI seemed to not follow player up/down slopes, expand range
1. What did you expect to happen?
Cats track and attack player, even when at different Y level
2. What actually happened instead (i.e. what was the bug)
Sat, spun some, and didn't move
https://clips.twitch.tv/MoistPricklyCasetteVoHiYo

Alc says "Moo pls fix"

**Meta Info**
 - TFC Version: 1.0.0.128 -- TFC Tuesday server

### LINKED ISSUE #1040: Viande texture
**Describe the bug**
2. What actually happened instead (i.e. what was the bug)
There is one odd red pixel in the cooked viande texture.

image

**Meta Info**
 - TFC Version: 0.X.X131

### LINKED ISSUE #1053: squid spawns and/or calamari drops should be nerfed
They spawn like crazy and drop way more food than in Classic by comparison. 

 - TFC Version: build 132

### LINKED ISSUE #1092: Fix Spawn egg colors.
TFC 133
Many spawn eggs are oddly colored and some are clearly copy paste from others.

### PR DESCRIPTION
**Pull request by Azaysol**
Animal Updates including Camel and Hyena

Fixes #1040 
Fixes #1006
Fixes #1053
Fixes #1092

### CODE REVIEW

**Comment by Azaysol** [comment]
@DisasterMoo remember to allow tfc chest for llamas and camels. also its late here, the hyena sounds should be working, but arent for some reason, take a look if u can. ill check it out tomorrow if not

**Comment by Azaysol** [comment]
fixed #1040 
although now its called hyena, since camels, llama and alpacas use camelidae

**Comment by Azaysol** [comment]
fixed Hyena sounds, just missing the tfc chest issue

File: src/main/java/net/dries007/tfc/objects/entity/animal/EntityCamelTFC.java [hunk 1]
```diff
@@ -12,40 +12,106 @@
...
 import net.dries007.tfc.objects.LootTablesTFC;
 import net.dries007.tfc.util.calendar.CalendarTFC;
 import net.dries007.tfc.util.climate.BiomeHelper;
 import net.dries007.tfc.world.classic.biomes.BiomesTFC;
 
+import static net.dries007.tfc.TerraFirmaCraft.MOD_ID;
+
 @ParametersAreNonnullByDefault
-public class EntityCamelTFC extends EntityLlamaTFC implements IAnimalTFC, ILivestock
+public class EntityCamelTFC extends EntityLlama implements IAnimalTFC, ILivestock
```
Comment (DisasterMoo) [inline src/main/java/net/dries007/tfc/objects/entity/animal/EntityCamelTFC.java]: Any reason for this change? You could save some copy-paste variables and functions in this class if you kept extending `EntityLlamaTFC`, while also having less code to maintain later. Another option could be extending `EntityHorseTFC` since this one should be mountable.

**Review by DisasterMoo — COMMENTED** [review]
Just a minor thing, otherwise seems good.

**Comment by Azaysol** [comment]
this also fixes #1006 #1053 and a part of #1073

File: src/main/java/net/dries007/tfc/client/render/animal/LayerCamelDecor.java [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
...MEL_DECOR_TEXTURES = new ResourceLocation[]{new ResourceLocation(MOD_ID, "textures/entity/animal/decor/white.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/orange.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/magenta.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/light_blue.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/yellow.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/lime.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/pink.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/gray.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/silver.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/cyan.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/purple.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/blue.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/brown.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/green.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/red.png"), new ResourceLocation(MOD_ID, "textures/entity/animal/decor/black.png")};
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/client/render/animal/LayerCamelDecor.java]:
```suggestion
    private static final ResourceLocation[] CAMEL_DECOR_TEXTURES = IntStream.range(0, 16).map(i -> new ResourceLocation(MOD_ID, "textures/entity/animal/decor/" + EnumDyeColor.byMetadata(i).etName() + ".png").toArray(ResourceLocation[]::new);
```
is much cleaner imo.

**Review by alcatrazEscapee — CHANGES_REQUESTED** [review]

**Review by alcatrazEscapee — APPROVED** [review]
