### PR TITLE
A few more fixes

### LINKED ISSUE #1166: TFCT: Forging Safety for blooms
#786 apparently applies to only ingots, as https://www.twitch.tv/pakratt0013/clip/ZealousPreciousNarwhalPupper
demonstrates. Blooms appear to already have been worked, as they are inheriting the "work" of their split parent.

**Meta Info**
 - TFC Version: 135
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

### LINKED ISSUE #1175: TFCT: Smithing bonus needs rounding
Should report percentage rounded to the nearest hundredth, instead of exact percentage to the 0.0000001% :)

https://clips.twitch.tv/FilthyArtisticQuailPJSalt

**Meta Info**
 - TFC Version: 135

### LINKED ISSUE #1188: Several crops report "Growing\nGrowth: Mature" in HWYLA when not at max growth state
**Describe the bug**
Make sure to include:
HYWLA says crop is mature, yet breaking yields only seed. Reproduced with Jute, Maize and Cabbages at least. Jute growth stage is 4, yet has 6 growth states according to the wiki and the code
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/23c40880d6ec3041ce9bcee0882e6dd676208969/src/main/java/net/dries007/tfc/util/agriculture/Crop.java#L56

**To Reproduce**
Attention to detail is important!
1. Let Jute (or other crop) grow to stage 4, note Hwyla says `Growing\nGrowth: Mature` yet crop is not actually mature
2. Break and only get seeds

**Meta Info**
 - TFC Version: 1.0.11.140
 - Wawla 2.6.275
 - Hwyla 1.8.26-B41

### LINKED ISSUE #1193: Add stack size check to ore stack total counter.
TFC 140
It's stupid repeating the same info and irritates me.
Make sure to check on both the small item and the ores. Only apply if it's more than one.

### LINKED ISSUE #1194: TFCT: bloomery doesn't complete
https://clips.twitch.tv/TubularHappyKimchiBudStar 
going for 40 in game minutes.

 - TFC Version: build 140

### LINKED ISSUE #1198: TFCT: Salting recipe issues on raw meat
Salting recipe doesn't apply Salting tag to raw meat
Salting recipes can be applied multiple times to same meat
Meat seems to stack after the recipe strangely.
https://clips.twitch.tv/HardSneakyJuiceWholeWheat

**Meta Info**
 - TFC Version: build 140

### PR DESCRIPTION
**Pull request by DisasterMoo**
- Reworked bloomery logic (Fixes #1194).
- Fixed traits tooltip and also made salting recipe only apply once (Closes #1198).
- Reworked melting units tooltip in ores and small ores (Closes #1193).
- Reworked Waila integration to Crops (Closes #1188).
- Smithing bonus now is rounded (Closes #1175).
- Fixed bloom's not resetting work properly on splitting recipes (Closes #1166).

### CODE REVIEW

File: src/main/java/net/dries007/tfc/api/recipes/anvil/AnvilRecipeSplitting.java [hunk 1]
```diff
@@ -68,8 +68,7 @@ public boolean matches(ItemStack input)
                     IForgeable cap = dump.getCapability(CapabilityForgeable.FORGEABLE_CAPABILITY, null);
                     if (cap instanceof IForgeableMeasurableMetal)
                     {
-                        cap.setWork(0); //Reset work without resetting temp
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/api/recipes/anvil/AnvilRecipeSplitting.java:71]: Does this not apply or is it already handled?

File: src/main/java/net/dries007/tfc/compat/waila/BloomeryProvider.java [hunk 2]
```diff
@@ -44,7 +44,7 @@
             {
                 List<ItemStack> oreStacks = bloomery.getOreStacks();
                 BloomeryRecipe recipe = oreStacks.size() > 0 ? BloomeryRecipe.get(oreStacks.get(0)) : null;
-                long remainingMinutes = Math.round(bloomery.getBurnTicksLeft() / 1200.0f);
+                long remainingMinutes = Math.round(bloomery.getReaminingTicks() / 1200.0f);
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/compat/waila/BloomeryProvider.java]:
```suggestion
                long remainingMinutes = Math.round(bloomery.getRemainingTicks() / 1200.0f);
```
Spelling

File: src/main/java/net/dries007/tfc/api/recipes/anvil/AnvilRecipeSplitting.java (hunk 1 above)
Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/api/recipes/anvil/AnvilRecipeSplitting.java:71]: `cap.reset()` does everything: reset steps, reset recipe and also set work to 0 (without resetting temperature)

File: src/main/java/net/dries007/tfc/compat/waila/BloomeryProvider.java (hunk 2 above)
Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/compat/waila/BloomeryProvider.java]: Typo 😛

**Review by alcatrazEscapee — APPROVED** [review]
