### PR TITLE
Fixed Broken Bubble Particles and Bubble Columns

### LINKED ISSUE #3245: Broken bubble particles
Bubble particles move much too fast in TFC fluids. This goes both for magma bubbles and spring water bubbles

### PR DESCRIPTION
**Pull request by trist79**
Closes https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/3245

Fixed Bubble Columns and Bubble Particles. Added ability for Spring Water to have bubble columns, fixed Spring Water's ambient bubbles animation

Rewrote TFCBubbleColumnBlock.java to make it work with all TFC Magma Blocks and whatever makes upwards bubble columns.

### CODE REVIEW

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java [hunk 1]
```diff
@@ -24,56 +28,156 @@
...
-        final BlockPos.MutableBlockPos cursor = abovePos.mutable();
+        FRESH_WATER(Fluids.WATER.getSource(), (TFCBubbleColumnBlock) TFCBlocks.FRESHWATER_BUBBLE_COLUMN.get()),
+        SALT_WATER(TFCFluids.SALT_WATER.getSource(), (TFCBubbleColumnBlock) TFCBlocks.SALTWATER_BUBBLE_COLUMN.get()),
+        SPRING_WATER(TFCFluids.SPRING_WATER.getSource(), (TFCBubbleColumnBlock) TFCBlocks.SPRING_WATER_BUBBLE_COLUMN.get());
+        final Fluid fluid;
+        final TFCBubbleColumnBlock block;
+        static final Map<Fluid, BubbleFluid> LOOKUP = Arrays.stream(values()).collect(Collectors.toMap(b -> b.fluid, b -> b)); // Maps fluids so you don't have to loop
+        BubbleFluid(Fluid f, TFCBubbleColumnBlock b) { block = b; this.fluid = f; }
+        static TFCBubbleColumnBlock of(Fluid f) { return LOOKUP.getOrDefault(f, BubbleFluid.FRESH_WATER).block; }
+    }
```
Comment (eerussianguy) [inline src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java]: Yo this is over-engineered. Do you work in enterprise java or something? As far as I can tell the application is to transform fluid to block. Ok, then an if with two elses would be perfect for this. Given that youve made it an enumyou're not providing any extensibility anyway by doing this.

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java [hunk 2]
```diff
@@ -24,56 +28,156 @@
...
+                level.setBlock(above, newColumn, Block.UPDATE_ALL);
             }
-
-            cursor.move(Direction.UP);
-            beforeState = level.getBlockState(cursor);
         }
-
+        boolean downBubbles = isDownBubbles(level, pos);
+        BlockPos.MutableBlockPos cursor = pos.mutable();
+        Direction direction = downBubbles ? Direction.DOWN : Direction.UP;
```
Comment (eerussianguy) [inline src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java]: `final`

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java [hunk 3]
```diff
@@ -24,56 +28,156 @@
...
+        cursor.move(direction);
+        while (true) {
+            if (cursor.getY() < level.getMinBuildHeight() || cursor.getY() >= level.getMaxBuildHeight()) break;
```
Comment (eerussianguy) [inline src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java]: I hate while true, but if you really want it you can have it

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java [hunk 4]
```diff
@@ -24,56 +28,156 @@
...
+                }
+                break;
+            }
+            if (state.getBlock() instanceof TFCMagmaBlock) break;
+            Fluid currentFluid = state.getFluidState().getType();
+            TFCBubbleColumnBlock columnBlock = BubbleFluid.of(currentFluid);
+            BlockState newColumn = columnBlock.defaultBlockState().setValue(BubbleColumnBlock.DRAG_DOWN, downBubbles);
+            if (!state.is(newColumn.getBlock())) {
+                level.setBlock(cursor, newColumn, Block.UPDATE_ALL);
+            } else break;
```
Comment (eerussianguy) [inline src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java]: Apply code style everywhere, particularly put all braces on newlines. We have a codestyle XML in the reop.

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java [hunk 5]
```diff
@@ -24,56 +28,156 @@
...
+                if (state.getBlock() instanceof TFCBubbleColumnBlock) {
+                    level.setBlock(cursor, state.getFluidState().createLegacyBlock(), Block.UPDATE_ALL);
+                }
+                break;
+            }
+            if (state.getBlock() instanceof TFCMagmaBlock) break;
+            Fluid currentFluid = state.getFluidState().getType();
+            TFCBubbleColumnBlock columnBlock = BubbleFluid.of(currentFluid);
+            BlockState newColumn = columnBlock.defaultBlockState().setValue(BubbleColumnBlock.DRAG_DOWN, downBubbles);
+            if (!state.is(newColumn.getBlock())) {
```
Comment (eerussianguy) [inline src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java]: `Helpers#isBlock` please

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java [hunk 6]
```diff
@@ -24,56 +28,156 @@
...
+
+            BlockState state = level.getBlockState(cursor);
+
+            if (!canExistIn(state)) {
+                if (state.getBlock() instanceof TFCBubbleColumnBlock) {
+                    level.setBlock(cursor, state.getFluidState().createLegacyBlock(), Block.UPDATE_ALL);
+                }
+                break;
+            }
+            if (state.getBlock() instanceof TFCMagmaBlock) break;
```
Comment (eerussianguy) [inline src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java]: can we put control statements on new lines when we can? We do not have a lack of lines available in the document.

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java [hunk 7]
```diff
@@ -24,56 +28,156 @@
...
+                double dx = Math.cos(angle) * radius;
+                double dz = Math.sin(angle) * radius;
+
+                double vx = -Math.sin(angle) * 0.02;
+                double vz = Math.cos(angle) * 0.02;
+
+                level.addParticle(TFCParticles.BUBBLE.get(), px + dx, py, pz + dz, vx, dy, vz);
+            }
+            else
+            { // Up Bubbles
```
Comment (eerussianguy) [inline src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java]: scary comment location

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java [hunk 8]
```diff
@@ -24,56 +28,156 @@
...
+                double time = (level.getGameTime() * 12.0 + phaseOffset * 360.0) % 360.0;
+                double angle = Math.toRadians(time);
+
+                double dx = Math.cos(angle) * radius;
+                double dz = Math.sin(angle) * radius;
+
+                double vx = -Math.sin(angle) * 0.02;
+                double vz = Math.cos(angle) * 0.02;
+
+                level.addParticle(TFCParticles.BUBBLE.get(), px + dx, py, pz + dz, vx, dy, vz);
```
Comment (eerussianguy) [inline src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java]: Use `Mth` for cos and sin operations since those use tables.

Is this a vanilla copy? Something you came up with? If it is a vanilla copy please notate that.,

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java [hunk 9]
```diff
@@ -96,44 +200,24 @@ public void tick(BlockState state, ServerLevel level, BlockPos pos, RandomSource
...
-        // Otherwise is identical
         final Fluid fluid = getFluid();
 
         level.scheduleTick(pos, fluid, fluid.getTickDelay(level));
-        if (!state.canSurvive(level, pos) ||
-            facing == Direction.DOWN ||
-            (facing == Direction.UP && !(facingState.getBlock() instanceof TFCBubbleColumnBlock) && canExistIn(facingState)))
+        if (!state.canSurvive(level, pos))
+        {
+            return fluid.defaultFluidState().createLegacyBlock();
```
Comment (eerussianguy) [inline src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java:187]: You have to return AIR here. Unless the vanilla method returns a fluid, this no longer works as of 1.21 because it needs AIR to actually "break" the block, and does the fluid functionality on its own without our input!

File: src/main/java/net/dries007/tfc/common/blocks/HotWaterBlock.java [hunk 10]
```diff
@@ -31,16 +31,14 @@ public HotWaterBlock(Supplier<? extends FlowingFluid> supplier, Properties prope
...
         double z = pos.getZ() + random.nextFloat();
-
-        //TODO: Bubble particles are buggy with TFC water types in all cases
-        if (random.nextInt(3) == 0)
-            level.addParticle(ParticleTypes.BUBBLE_COLUMN_UP, x, y + random.nextFloat(), z, 0.0, 0.04, 0.0);
-
         if (level.isEmptyBlock(pos.above()))
             level.addParticle(TFCParticles.STEAM.get(), x, y + 1.0D, z, 0.0D, 0.0D, 0.0D);
+        if (bubbleState.getBlock() instanceof TFCBubbleColumnBlock bubbleBlock && bubbleBlock.isDownBubbles(level, pos)) return;
+        if (random.nextInt(3) == 0) level.addParticle(TFCParticles.BUBBLE.get(), x, y + random.nextFloat(), z, 0.0, 0.04, 0.0);
```
Comment (eerussianguy) [inline src/main/java/net/dries007/tfc/common/blocks/HotWaterBlock.java]: lets get some newlines in here

**Review by eerussianguy — CHANGES_REQUESTED** [review]

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java (hunk 1 above)
Comment (trist79) [reply src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java]: I made an enum so I could use switch statements instead of repeated if else. Not completely necessarily, I just like using switch cases, and java makes it a bit harder to utilize them. I thought I would need more switches in the logic but I only ended up using it a few times. 

The of() function takes in a TFCBubbleColumnBlock and returns the fluid that is inside it. I used a couple of times in the code. 

The map is so that you don't have to loop through every time so it saves a little bit on time complexity. It would improve performance in situations where there are tons of bubble columns.

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java (hunk 3 above)
Comment (trist79) [reply src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java]: I'm with you there hating perma loops, and I'd happy to change it but I couldn't figure out a better way to do so in this case.

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java (hunk 4 above)
Comment (trist79) [reply src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java]: I use VSCode so I had to manually apply code styling. Missed this one!

File: src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java (hunk 8 above)
Comment (trist79) [reply src/main/java/net/dries007/tfc/common/blocks/TFCBubbleColumnBlock.java]: This isn't the vanilla copy as that's not publicly available. This was my attempt to reproduce it and it's somewhat close. 

I'm not a mathematician so this is just derived from some circular particle logic I found on Google

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/2d1445c842eaedd38fcf2c4a7fdf47443f01bfc3

In case you want to see my changes to your PR. There was also a major missed nullability issue, make sure your IDE has warnings turned on. The getOrDefault method can't return null, but you were null checking.

**Comment by trist79** [comment]
> [2d1445c](https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/2d1445c842eaedd38fcf2c4a7fdf47443f01bfc3)
> 
> In case you want to see my changes to your PR. There was also a major missed nullability issue, make sure your IDE has warnings turned on. The getOrDefault method can't return null, but you were null checking.

No problem. Thanks for the fix and review!
