### PR TITLE
Another bug fixing PR

### LINKED ISSUE #367: Unfired colored vessels lack a recipe
It is currently impossible to craft a colored vessel.

Putting an unfired small vessel and a dye in the crafting grid will result in nothing, regardless of crafting shape.

Failed crafting

JEI displays the Usage for unfired colored vessels but not the Recipe to make them.

JEI UI

**Mods**
 - TerraFirmaCraft 0.22.4.66
 - CodeChicken Lib 3.2.3.357
 - Just Enough Items 4.15.0.268
 - Not Enough Items 2.4.3.245

### PR DESCRIPTION
**Pull request by DisasterMoo**
Closes #367 by assets PR

### CODE REVIEW

File: src/main/java/net/dries007/tfc/objects/items/ceramics/ItemJug.java [hunk 1]
```diff
@@ -95,7 +95,7 @@ else if (!world.isRemote && jugCap.drain(CAPACITY, false) == null && rayTrace !=
                 }
                 else
                 {
-                    player.world.playSound(null, player.getPosition(), TFCSounds.JUG_BLOW, SoundCategory.PLAYERS, 1.0f, 1.0f);
+                    player.world.playSound(null, player.getPosition(), TFCSounds.JUG_BLOW, SoundCategory.PLAYERS, 1.0f, Constants.RNG.nextFloat() * 0.3f + 0.8f);
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/items/ceramics/ItemJug.java]: This is not the player yaw - the intent is to make it make different sounds based on what direction you face up / down.
