### PR TITLE
Another round of fixes

### LINKED ISSUE #515: Config Reorganization
Current config setup is divided into three categories: General, World, and Client. The latter two are sufficient categories, however the General section is becoming quite large (which makes it difficult to scroll through for specific config options), and unorganized. We'd also like to open up a lot more things to be configurable, so ideally this would happen before the config gets too large. I'd propose a few separate categories:

 - General (for misc. config stuff that still fits here)
 - Balance (for balance related tweaks, changing numbers, etc.)
 - Mechanics (for enabling / disabling mechanics, or changing how the mod functions)
 - Packmakers (a section for options that are more technical, and basically only exist for pack makers. i.e. `crushingDamageSources`)

### LINKED ISSUE #1093: Polar bears attacking causes a crash.
TFC 133
https://pastebin.com/BnAwcTkA

### LINKED ISSUE #1211: TFCT: Sapling and fruit tree growth status should be displayed by WAILA/TOP interfaces
We should at least display how many days ago a sapling was planted. Fruit trees could display time to next stage or something?

 - TFC Version: build 140

### LINKED ISSUE #1216: Rotten food negative effects dont actually work
When eating rotten food you get hunger and poison effects, but those dont lower your hunger bar nor do damage.

**Meta Info**
 - TFC Version: 1.0.11.140
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

### LINKED ISSUE #1219: Vessel containing liquid in campfire
If you put a vessel containing molten copper (don't know if it works with other ores) in a campfire, the copper disapear (the units aren't displayed anymore and the vessel acts if there was any copper)

### LINKED ISSUE #1220: Brining and pickling keep repeating
**Describe the bug**
1. What did you expect to happen?
When an item is finished brining or pickling in a barrel, it uses up an appropriate amount of brine/vinegar and then can be left in the barrel indefinitely without using up more brine/vinegar
2. What actually happened instead (i.e. what was the bug)
When brining/pickling finishes, the barrel sealed date updates to the current date and after another 4 hours, it uses more brine/vinegar.

**To Reproduce**
1. Fill a barrel with brine.
2. Put some brineable food into the barrel.
3. Wait 4 in-game hours, observe the barrel GUI
4. Wait another 4 in-game hours, observe the barrel again.

**Meta Info**
 - TFC Version: 1.0.12.141
 - I tested it on TFC only.

### LINKED ISSUE #1225: Can't use chest on donkey/mule to make 'saddlebags'
Can't use chest on donkey/mule to make 'saddlebags'

**Meta Info**
 - TFC Version: 0.X.X.141 on test server

### LINKED ISSUE #1226: Firepit damages you even when not touching the model
141. I was jumping over the fire pit, because I was trying to get into character, but I noticed that it actually damages you when you're occupying the same block as it, not when you're touching the model. Can anyone else confirm?

### LINKED ISSUE #1228: Unintended uses for rotten food
Ive found 2 ways in which rotten food can be used that i assume are not intentional:
-Vinegar from rotten fruit
You can use rotten fruit to make vinegar, no differences from normal fruit
-Rotten food sandwiches
You can put 3 rotten foods in a sandwich (i havent tried to make it using rotten bread too) and the sandwich will not be rotten
I assume when making a sandwich it makes an average of the decay of all the ingredients, and since the bread still had a long time before becoming rotten it made up for the rotten food.

**Meta Info**
 - TFC Version: 1.0.12.141

### LINKED ISSUE #1229: Animals going through fences
Sometime i find that one of my animals has gone through the fence is outside, im not sure how to replicate it becasue ive never seen it happen, ive always just found the animals outside the fenced area

**Meta Info**
 - TFC Version: 1.0.12.141
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

### LINKED ISSUE #1231: Baby goat models float above the ground.
**Describe the bug**
The floating baby mobs return!
**Meta Info**
 - TFC Version:1.12.2-1.0.12.141

### LINKED ISSUE #1232: Maize should follow other grains processing steps
I think corn flour should be made from corn grains and not the corn maize, this would allow people to keep the grain for longer as the maize rots a lot faster as well as get the straw from it, most importantly, its more realistic, as you dont make frour by putting a whole maze of cord into a quern

**Meta Info**
 - TFC Version: 1.0.12.141 (at time of request)

### PR DESCRIPTION
**Pull request by DisasterMoo**
- Fixed #1216 by checking for server side
- Fixed a minor issue in TOP tooltips
- Fixed #1219 by adding a missing `copy()` stack item small vessel firing recipe (fire pit shrink stacks)
- Fixed #1225 by allowing TFC chests to be used
- Fixed #1231
- Fixed #1232 by making maizes follow other grains
- Fixed #1228 by adding a new `IIngredient` implementation that checks for not rotten foods
- Fixed #1220 by checking if brining or picking food has the trait already
- May have Fixed #1229 by making server side update hitboxes once per day / when animal eats.
- Added more info to fruit trees and berry bushes (Closes #1211)
- Fixed #1093 by changing conflicting function signatures between `IEntityStandAttack` and vanilla's polar bear.
- Config reorganization (Closes #515)

### CODE REVIEW

File: src/main/java/net/dries007/tfc/objects/blocks/devices/BlockFirePit.java [hunk 1]
```diff
@@ -274,25 +274,14 @@ else if (tile.getCookingPotStage() == TEFirePit.CookingPotStage.FINISHED)
...
-    public void onEntityWalk(World worldIn, BlockPos pos, Entity entityIn)
-    {
-        IBlockState state = worldIn.getBlockState(pos);
-        if (state.getValue(LIT) && !entityIn.isImmuneToFire() && entityIn instanceof EntityLivingBase)
-        {
-            entityIn.attackEntityFrom(DamageSource.IN_FIRE, 1.0F);
-        }
-        super.onEntityWalk(worldIn, pos, entityIn);
-    }
-
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/blocks/devices/BlockFirePit.java]: This was intentionally added to fix #1025, which the result behavior was that fire pits only damaged you in very select circumstances. Is the problem not the below change to the wrong `super` call?

Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/objects/blocks/devices/BlockFirePit.java]: Oh, no that wrong super call did nothing. Looking at the call chain the default implementation of both methods does nothing. Now, removing `#onEntityWalk` fixed. 

Looking at the call chain, `#onEntityWalk` is called from `Entity#move()L1039` when said entity is in the block or one block above it if the above block is empty/AIR, so, if there is no other way to fix #1025 we're gonna have to choose which one stays fixed.

Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/objects/blocks/devices/BlockFirePit.java]: Removed fix as per discord discussion

File: src/main/java/net/dries007/tfc/objects/blocks/agriculture/BlockFruitTreeTrunk.java [hunk 2]
```diff
@@ -58,7 +58,7 @@ public static BlockFruitTreeTrunk get(IFruitTree tree)
         return MAP.get(tree);
     }
 
-    private final IFruitTree tree;
+    public final IFruitTree tree;
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/blocks/agriculture/BlockFruitTreeTrunk.java]: Hey. Where be my `getFruitTree` with private behind the scenes fields!

Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/objects/blocks/agriculture/BlockFruitTreeTrunk.java]: Fine fine, I also thought on doing it properly, but.... this means i have to do the same thing in 99999 other classes that also has this inconsistency 😨 

(numbers may be a jest, but there are some other blocks that have a public property field that should be private with a getter)

Welp, time to mark this PR as a draft and start refactoring!

File: src/main/java/net/dries007/tfc/objects/te/TETickCounter.java [hunk 3]
```diff
@@ -25,12 +25,14 @@ public long getTicksSinceUpdate()
     public void resetCounter()
     {
         lastUpdateTick = CalendarTFC.PLAYER_TIME.getTicks();
+        markForSync();
         markDirty();
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/te/TETickCounter.java]: `markForSync` already calls `markDirty`, no need to call both here. Same as below

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 4]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            public int normalOreMetalAmount = 25;
+
+            @Config.Comment("The amount of metal contained in a rich ore.")
+            @Config.LangKey("config." + MOD_ID + ".general.misc.richOreMetalAmount")
+            @Config.RangeInt(min = 1, max = 10_000)
+            public int richOreMetalAmount = 35;
+
+            @Config.Comment("Enable ingot pile placement in world.")
+            @Config.LangKey("config." + MOD_ID + ".general.misc.enableIngotPiles")
+            public boolean enableIngotPiles = true;
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: Should be in overrides, as it's a binary enable/disable of a feature.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 5]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            public String[] crushingEntities = new String[] {"minecraft:husk", "minecraft:skeleton_horse", "minecraft:zombie_horse", "minecraft:spider", "minecraft:giant", "minecraft:zombie", "minecraft:slime", "minecraft:cave_spider", "minecraft:silverfish", "minecraft:villager_golem", "minecraft:zombie_villager"};
+        }
+
+        public static final class PlayerCFG
+        {
+            @Config.Comment("Enable a 3x3 crafting inventory via key binding.")
+            @Config.LangKey("config." + MOD_ID + ".general.player.inventoryCraftingMode")
+            public InventoryCraftingMode inventoryCraftingMode = InventoryCraftingMode.ENABLED;
+
+            @Config.Comment("Minimum health modifier player can obtain with low nutrition.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: Include math. Example: Player health * this number = minimum health

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 6]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+
+            @Config.Comment("Enable/Disable the vanilla recipe removal spam. False = Those recipes are left in place.")
+            @Config.LangKey("config." + MOD_ID + ".general.overrides.removeVanillaRecipes")
+            public boolean removeVanillaRecipes = true;
+
+            @Config.Comment("Enable/Disable the vanilla loot entries that conflict with TFC (ie: potatoes). False = Those loot entries are left in place.")
+            @Config.LangKey("config." + MOD_ID + ".general.overrides.removeVanillaLoots")
+            public boolean removeVanillaLoots = true;
+
+            @Config.Comment({"If true, this will force the gamerule naturalRegeneration to be false. ", "Note: this DOES NOT AFFECT TFC's natural regeneration. If you set naturalRegeneration to true, then you will have both TFC regeneration and normal vanilla regeneration (which is much faster)"})
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: This should have an enter in it at the end of the comment line so it's clear it's two lines.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 7]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+
+            @Config.Comment("Should logs require tools (axes and saws, or hammers for sticks) to be cut? If false, breaking logs with an empty hand will not drop logs.")
+            @Config.LangKey("config." + MOD_ID + ".general.tree.requiresAxe")
+            public boolean requiresAxe = true;
+
+            @Config.Comment("If false, leaves will not drop saplings.")
+            @Config.LangKey("config." + MOD_ID + ".general.tree.enableSaplings")
+            public boolean enableSaplings = true;
+
+            @Config.Comment("Log return rate of stone axes (eg: How efficiently it is)")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: efficient not efficiently
```suggestion
            @Config.Comment("Chance per log for an item to drop when using a stone axe.")
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 8]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeDouble(min = 0, max = 1)
+            @Config.LangKey("config." + MOD_ID + ".general.tree.leafStickDropChance")
+            public double leafStickDropChance = 0.1;
+
+            @Config.Comment("Bonus leaf drop chance for sticks")
+            @Config.RangeDouble(min = 0, max = 1)
+            @Config.LangKey("config." + MOD_ID + ".general.tree.leafStickDropChanceBonus")
+            public double leafStickDropChanceBonus = 0.25;
+
+            @Config.Comment("Bonus leaf drop stick chance for sticks tool classes")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: Should include info on how to find these.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 9]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.tree.leafStickDropChanceBonusClasses")
+            public String[] leafStickDropChanceBonusClasses = new String[] {"knife", "scythe"};
+        }
+
+        public static final class SpawnProtectionCFG
+        {
+            @Config.Comment("Should living in a chunk block hostile mob and predators spawning over time?")
+            @Config.LangKey("config." + MOD_ID + ".general.spawn_protection.enable")
+            public boolean enable = true;
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: Should likely split this in two. One for Hostiles and one for predators.
This ties into the Y check option as it would allow people to set the Y to zero and only block underground mobs if they wish.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 10]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+
+            @Config.Comment("The min Y value a spawn has to be for spawn protection to be considered. (spawns under this level won't be stopped by spawn protection.")
+            @Config.RangeInt(min = 1, max = 255)
+            @Config.LangKey("config." + MOD_ID + ".general.spawn_protection.minY")
+            public int minY = 100;
+        }
+
+        public static final class DamageCFG
+        {
+            @Config.Comment("Damage Source Types that will default to Slashing damage.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java:266]: How to get them? This goes for all of the following areas too. If we don't have a tool built into TFC to get the required entries something should be added and explained.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 11]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.damage.slashingSources")
+            public String[] slashingSources = new String[] {};
+
+            @Config.Comment("Damage Source Types that will default to Piercing damage.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java:270]: How to get them?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 12]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.damage.piercingSources")
+            public String[] piercingSources = new String[] {"arrow", "cactus", "thorns"};
+
+            @Config.Comment("Damage Source Types that will default to Crushing damage.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java:274]: How to get them?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 13]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.damage.crushingSources")
+            public String[] crushingSources = new String[] {"anvil", "falling_block"};
+
+            @Config.Comment("Damage Source Entities that will default to Slashing damage.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java:278]: How to get them?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 14]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.damage.slashingEntities")
+            public String[] slashingEntities = new String[] {"minecraft:wither_skeleton", "minecraft:vex", "minecraft:vindication_illager", "minecraft:zombie_pigman", "minecraft:wolf", "minecraft:polar_bear"};
+
+            @Config.Comment("Damage Source Entities that will default to Piercing damage.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java:282]: How to get them?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 15]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.damage.piercingEntities")
+            public String[] piercingEntities = new String[] {"minecraft:stray", "minecraft:skeleton"};
+
+            @Config.Comment("Damage Source Entities that will default to Crushing damage.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java:286]: How to get them?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 16]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.Comment("Enable a 3x3 crafting inventory via key binding.")
+            @Config.LangKey("config." + MOD_ID + ".general.player.inventoryCraftingMode")
+            public InventoryCraftingMode inventoryCraftingMode = InventoryCraftingMode.ENABLED;
+
+            @Config.Comment("Minimum health modifier player can obtain with low nutrition.")
+            @Config.RangeDouble(min = 0.1d, max = 1d)
+            @Config.LangKey("config." + MOD_ID + ".general.player.minHealthModifier")
+            public double minHealthModifier = 0.2d;
+
+            @Config.Comment("Maximum health modifier player can obtain with high nutrition.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: Include math. Example: Player health * this number = total health.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 17]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeDouble(min = 1d, max = 5d)
+            @Config.LangKey("config." + MOD_ID + ".general.player.maxHealthModifier")
+            public double maxHealthModifier = 3d;
+
+            @Config.Comment("Modifier for how quickly the players becomes thirsty.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: Include comparison values. What is 8? 8x? 8 x another number? How does it compare to vanilla hunger for example.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 18]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeDouble(min = 0, max = 100)
+            @Config.LangKey("config." + MOD_ID + ".general.player.thirstModifier")
+            public double thirstModifier = 8.0;
+
+            @Config.Comment("Modifier for how quickly the player will naturally regenerate health.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: Include comparison values. Is 1 vanilla?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 19]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.player.naturalRegenerationModifier")
+            @Config.RangeDouble(min = 0, max = 100)
+            public double naturalRegenerationModifier = 1.0;
+
+            @Config.Comment("Should the player receive passive regeneration of health, food, and thirst, while in peaceful mode similar to vanilla?")
+            @Config.LangKey("config." + MOD_ID + ".general.player.peacefulDifficultyPassiveRegeneration")
+            public boolean peacefulDifficultyPassiveRegeneration = false;
+
+            @Config.Comment("A multiplier for passive exhaustion (how fast your hunger decays. 0 = hunger doesn't decay passively, higher values = faster decay).")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: Include comparison values. Is this a multiplier on vanilla values?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 20]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.player.passiveExhaustionMultiplier")
+            @Config.RangeDouble(min = 0, max = 100)
+            public double passiveExhaustionMultiplier = 1;
+
+            @Config.Comment("This is the amount of hunger (consumed) required for a player to completely refresh their nutrition stats. In TFC, almost all foods have 4 hunger, so this is 4x [number of foods required to refresh nutrition stats]. This will update next time you consume a food.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: This is confusing.
```suggestion
            @Config.Comment(
"The amount of replenished hunger before the player's nutrition will lose the first food consumed. Most TFC foods have 4 hunger.", 
"Example: Multiply Vanilla hunger(20) by 4 to get one food bars worth of food before the first food is lost from the cycle." )
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 21]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+
+            @Config.Comment("Which inventory slots will ammo refill/pickup search for quivers?")
+            @Config.LangKey("config." + MOD_ID + ".general.player.quiverSearch")
+            public QuiverSearch quiverSearch = QuiverSearch.HOTBAR;
+        }
+
+        public static final class WorldCFG
+        {
+            @Config.RequiresMcRestart
+            @Config.Comment({"This controls how the temperature gradient appears near the equator.", "1: south of equator is hot, north of equator is cold", "-1: south of equator is cold, north of equator is hot"})
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]:
```suggestion
            @Config.Comment("Sets temperature in relation to the equator change. North = Cold, South = Hot or North = Hot, South = Cold")
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 22]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.world.hemisphereType")
+            public HemisphereType hemisphereType = HemisphereType.COLD_NORTH_HOT_SOUTH;
+
+            @Config.RequiresMcRestart
+            @Config.Comment("This controls how temperature is affected by how far from equator you are.")
+            @Config.LangKey("config." + MOD_ID + ".general.world.temperatureMode")
+            public TemperatureMode temperatureMode = TemperatureMode.CYCLIC;
+
+            @Config.Comment({"This controls the size of the temperature regions. The size of each temperature zone is determined by a sin wave. This represents the period of the wave."})
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: Perhaps a better explanation could be done here for people who don't understand sine waves?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 23]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeInt(min = 1, max = 500)
+            @Config.LangKey("config." + MOD_ID + ".general.world.clayRainfallThreshold")
+            public int clayRainfallThreshold = 150;
+
+            @Config.Comment("The number of attempts per chunk to spawn loose rocks. Includes surface ore samples.")
+            @Config.RangeInt(min = 1)
+            @Config.LangKey("config." + MOD_ID + ".general.world.looseRocksFrequency")
+            public int looseRocksFrequency = 18;
+
+            @Config.Comment("This controls how deep loose rocks scans for veins when generating. Higher values = more ore samples.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]:
```suggestion
            @Config.Comment("This is how deep in blocks from the surface a loose rock will scan for a vein when generating, Higher values = More veins spawn samples thus adding more samples.")
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 24]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeInt(min = 1, max = 255)
+            @Config.LangKey("config." + MOD_ID + ".general.world.looseRockScan")
+            public int looseRockScan = 35;
+
+            @Config.RequiresMcRestart
+            @Config.RangeDouble(min = 0.05, max = 0.4)
+            @Config.Comment("This controls how spread the rainfall distribution is. Higher values mean the world will be distributed towards the extremes more. WARNING: This is can cause very weird world generation conditions.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: This comment should be improved. What are the "extremes"?
I don't know enough about it to correct it.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 25]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.world.rainfallSpreadFactor")
+            public double rainfallSpreadFactor = 0.13;
+
+            @Config.RequiresMcRestart
+            @Config.RangeDouble(min = 0.05, max = 0.4)
+            @Config.Comment("This controls how spread the flora diversity distribution is. Higher values mean the world will be distributed towards the extremes more. WARNING: This is can cause very weird world generation conditions.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: This comment should be improved. What are the "extremes"?
I don't know enough about it to correct it.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 26]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.world.floraDiversitySpreadFactor")
+            public double floraDiversitySpreadFactor = 0.16;
+
+            @Config.RequiresMcRestart
+            @Config.RangeDouble(min = 0.05, max = 0.4)
+            @Config.Comment("This controls how spread the flora density distribution is. Higher values mean the world will be distributed towards the extremes more. WARNING: This is can cause very weird world generation conditions.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: This comment should be improved. What are the "extremes"?
I don't know enough about it to correct it.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 27]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.world.floraDensitySpreadFactor")
+            public double floraDensitySpreadFactor = 0.16;
+
+            @Config.RequiresMcRestart
+            @Config.Comment({"This controls which registered entities can respawn in TFC biomes.",
+                "You must specify by following the pattern 'modid:entity <rarity> <minGroupSpawn> <maxGroupSpawn>'",
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java:408]: How to get entity ID?
What conditions does respawn use?
If it fails there should be a logline generated and an example of it added here.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 28]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+                "Invalid entries will be ignored."})
+            @Config.LangKey("config." + MOD_ID + ".general.world.respawnableCreatures")
+            public String[] respawnableCreatures = {"tfc:beartfc 30 1 2", "tfc:polarbeartfc 30 1 2", "tfc:panthertfc 30 1 2", "tfc:sabertoothtfc 30 1 2", "tfc:liontfc 30 1 2", "tfc:hyenatfc 30 3 6", "tfc:pheasanttfc 70 2 3", "tfc:deertfc 70 2 4", "tfc:wolftfc 70 2 4", "tfc:parrottfc 70 2 3", "tfc:ocelottfc 70 2 4"};
+        }
+
+        public static final class WorldRegenCFG
+        {
+            @Config.Comment("The minimum time for a chunk to be unoccupied for it's resources to begin to naturally regenerate. (In days). After this amount, regeneration will scale up based on how long since this duration, up to a maximum of 4x")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: What resources? Currently this sounds like the whole chunk regenerates slowly over time.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 29]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeDouble(min = 0, max = 1)
+            @Config.LangKey("config." + MOD_ID + ".general.misc.leafMovementModifier")
+            public double leafMovementModifier = 0.1;
+
+            @Config.Comment("Berry bush movement modifier. Lower = Slower, Higher = Faster. 1 = No slow down. (Speed * this = slow)")
+            @Config.RangeDouble(min = 0, max = 1)
+            @Config.LangKey("config." + MOD_ID + ".general.misc.berryBushMovementModifier")
+            public double berryBushMovementModifier = 0.1;
+
+            @Config.Comment("Generic snow movement modifier. Lower = Slower, Higher = Faster. 1 = No slow down.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: Add math to match leafs and bush.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 30]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            public double fruitTreeGrowthTimeModifier = 1.0;
+        }
+
+        public static final class MiscCFG
+        {
+            @Config.Comment("The default length of a month (in days) when a new world is started. This can be changed in existing worlds via the /timetfc command.")
+            @Config.LangKey("config." + MOD_ID + ".general.misc.defaultMonthLength")
+            public int defaultMonthLength = 8;
+
+            @Config.Comment("Percentage chance that plants (not crops) grow each update. Smaller number = slower growth.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: This needs to be explained better.
```suggestion
            @Config.Comment("Chance for a plant to grow each random tick, does not include crops. Lower = slower growth."")
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 31]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeDouble(min = 0, max = 1)
+            @Config.LangKey("config." + MOD_ID + ".general.misc.snowMovementModifier")
+            public double snowMovementModifier = 0.85;
+
+            @Config.Comment("Generic movement modifier. Lower = Slower, Higher = Faster. 1 = No slow down. Note: this is a little different than other densities (leaf / berry bush), because this actually functions as a maximum slow down. Actual value is dependent on the plant and it's age.")
+            @Config.RangeDouble(min = 0, max = 1)
+            @Config.LangKey("config." + MOD_ID + ".general.misc.minimumPlantMovementModifier")
+            public double minimumPlantMovementModifier = 0;
+
+            @Config.Comment("Drop chance for gem from raw stone")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: This should include how to find the chance per grade of gem if that is also factored in.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 32]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+
+            @Config.Comment("Add iron ore dictionary to wrought iron?")
+            @Config.LangKey("config." + MOD_ID + ".general.misc.dictionaryIron")
+            public boolean dictionaryIron = false;
+
+            @Config.Comment("Add plate ore dictionary to sheets?")
+            @Config.LangKey("config." + MOD_ID + ".general.misc.dictionaryPlates")
+            public boolean dictionaryPlates = false;
+
+            @Config.Comment("List of fluids allowed to be picked up by wooden bucket")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java:544]: How to find the options?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 33]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.misc.woodenBucketWhitelist")
+            public String[] woodenBucketWhitelist = new String[] {"fresh_water", "hot_water", "salt_water", "water", "limewater", "tannin", "olive_oil", "vinegar", "rum", "beer", "whiskey", "rye_whiskey", "corn_whiskey", "sake", "vodka", "cider", "brine", "milk", "milk_curdled", "milk_vinegar", "white_dye", "orange_dye", "magenta_dye", "light_blue_dye", "yellow_dye", "lime_dye", "pink_dye", "gray_dye", "light_gray_dye", "cyan_dye", "purple_dye", "blue_dye", "brown_dye", "green_dye", "red_dye", "black_dye"};
+
+            @Config.Comment("List of fluids allowed to be picked up by blue steel bucket")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java:548]: How to find the options?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 34]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.Comment("The amount of metal contained in a rich ore.")
+            @Config.LangKey("config." + MOD_ID + ".general.misc.richOreMetalAmount")
+            @Config.RangeInt(min = 1, max = 10_000)
+            public int richOreMetalAmount = 35;
+
+            @Config.Comment("Enable ingot pile placement in world.")
+            @Config.LangKey("config." + MOD_ID + ".general.misc.enableIngotPiles")
+            public boolean enableIngotPiles = true;
+
+            @Config.Comment("Add iron ore dictionary to wrought iron?")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: This should include the tags it adds.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 35]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.misc.dictionaryIron")
+            public boolean dictionaryIron = false;
+
+            @Config.Comment("Add plate ore dictionary to sheets?")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: This should include the tags it adds.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 36]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+
+            @Config.Comment("List of fluids allowed to be picked up by wooden bucket")
+            @Config.LangKey("config." + MOD_ID + ".general.misc.woodenBucketWhitelist")
+            public String[] woodenBucketWhitelist = new String[] {"fresh_water", "hot_water", "salt_water", "water", "limewater", "tannin", "olive_oil", "vinegar", "rum", "beer", "whiskey", "rye_whiskey", "corn_whiskey", "sake", "vodka", "cider", "brine", "milk", "milk_curdled", "milk_vinegar", "white_dye", "orange_dye", "magenta_dye", "light_blue_dye", "yellow_dye", "lime_dye", "pink_dye", "gray_dye", "light_gray_dye", "cyan_dye", "purple_dye", "blue_dye", "brown_dye", "green_dye", "red_dye", "black_dye"};
+
+            @Config.Comment("List of fluids allowed to be picked up by blue steel bucket")
+            @Config.LangKey("config." + MOD_ID + ".general.misc.blueSteelBucketWhitelist")
+            public String[] blueSteelBucketWhitelist = new String[] {"lava"};
+
+            @Config.Comment("List of fluids allowed to be picked up by red steel bucket")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java:552]: How to find the options?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 37]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.LangKey("config." + MOD_ID + ".general.misc.redSteelBucketWhitelist")
+            public String[] redSteelBucketWhitelist = new String[] {"fresh_water", "hot_water", "salt_water", "water"};
+
+            @Config.Comment("Entities that can be plucked for feathers.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java:556]: (I made this one and still screwed it up)
How to find the names?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 38]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+        {
+            @Config.Comment("How much fluid (mB) can a barrel hold?")
+            @Config.RangeInt(min = 100)
+            @Config.LangKey("config." + MOD_ID + ".devices.barrel.tank")
+            public int tank = 10_000;
+        }
+
+        public static final class BlastFurnaceCFG
+        {
+            @Config.Comment("How fast the blast furnace consume fuels (compared to the charcoal forge).")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: Needs maths.

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 39]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeInt(min = 1)
+            @Config.LangKey("config." + MOD_ID + ".devices.lamp.tank")
+            public int tank = 250;
+
+            @Config.Comment("How fast lamps consume fuel (mb/hour)? 1 = lamp life of 1 hour per mB, 0.125 = lamp life of 2000 hours by default, 0 = infinite fuel")
+            @Config.RangeDouble(min = 0)
+            @Config.LangKey("config." + MOD_ID + ".devices.lamp.burnRate")
+            public double burnRate = 0.125;
+
+            @Config.Comment("Which fluids are valid fuels for lamps?")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java:706]: How to get values?

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 40]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+        @Config.LangKey("config." + MOD_ID + ".animals.pheasant")
+        public static final PheasantCFG PHEASANT = new PheasantCFG();
+
+        @Config.Comment("Rabbit")
+        @Config.LangKey("config." + MOD_ID + ".animals.rabbit")
+        public static final RabbitCFG RABBIT = new RabbitCFG();
+
+        public static final class AlpacaCFG
+        {
+            @Config.Comment("How many days it is needed for this animal to be considered a fully grown adult?")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: I'm only going to do this one animal bit. If you want to change them, copy paste to the rest, too many to mark.

```suggestion
            @Config.Comment("How many days until this animal is a full grown adult?")
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 41]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeInt(min = 1)
+            @Config.LangKey("config." + MOD_ID + ".animals.adulthood")
+            public int adulthood = 192;
+
+            @Config.Comment("How many more days it is needed for this animal to be considered an elder? 0 = Disable")
+            @Config.RangeInt(min = 0)
+            @Config.LangKey("config." + MOD_ID + ".animals.elder")
+            public int elder = 768;
+
+            @Config.Comment("How many days it is needed for this animal finish a gestation period?")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]:
```suggestion
            @Config.Comment("How many days until this animal gives birth?")
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 42]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeInt(min = 1)
+            @Config.LangKey("config." + MOD_ID + ".animals.gestation")
+            public int gestation = 59;
+
+            @Config.Comment("How many babies are born when this animal finishes gestation?")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]:
```suggestion
            @Config.Comment("How many babies are born when this animal gives birth?")
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 43]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+        public static final RabbitCFG RABBIT = new RabbitCFG();
+
+        public static final class AlpacaCFG
+        {
+            @Config.Comment("How many days it is needed for this animal to be considered a fully grown adult?")
+            @Config.RangeInt(min = 1)
+            @Config.LangKey("config." + MOD_ID + ".animals.adulthood")
+            public int adulthood = 192;
+
+            @Config.Comment("How many more days it is needed for this animal to be considered an elder? 0 = Disable")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]:
```suggestion
            @Config.Comment("How many days after becoming an adult until this animal is old? 0 = Disable")
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 44]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeInt(min = 1)
+            @Config.LangKey("config." + MOD_ID + ".animals.gestation")
+            public int gestation = 59;
+
+            @Config.Comment("How many babies are born when this animal finishes gestation?")
+            @Config.RangeInt(min = 1)
+            @Config.LangKey("config." + MOD_ID + ".animals.babies")
+            public int babies = 1;
+
+            @Config.Comment("How many ticks it is needed for this animal grow back wool?")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]:
```suggestion
            @Config.Comment("How many ticks are needed for this animal grow back wool?")
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 45]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeInt(min = 1_000)
+            @Config.LangKey("config." + MOD_ID + ".animals.woolTicks")
+            public int woolTicks = 96_000;
+
+            @Config.Comment("If this animal is an elder, what is the chance it is gonna die on every new day? 0 = Disable")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]:
```suggestion
            @Config.Comment("Chance that old animals will die at the start of a new day. 0 = Disable")
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 46]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+        public static final SmallVesselCFG SMALL_VESSEL = new SmallVesselCFG();
+
+        @Config.Comment("Sluice")
+        @Config.LangKey("config." + MOD_ID + ".devices.sluice")
+        public static final SluiceCFG SLUICE = new SluiceCFG();
+
+
+        public static final class TemperatureCFG
+        {
+            @Config.Comment("Modifier for how quickly items gains and loses heat. Smaller number = slower temperature changes.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]:
```suggestion
            @Config.Comment("Modifier for how quickly items will gain or lose heat. Smaller number = slower temperature changes.")
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 47]
```diff
@@ -46,614 +31,1423 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
...
+            @Config.RangeDouble(min = 0, max = 10)
+            @Config.LangKey("config." + MOD_ID + ".devices.temperature.globalModifier")
+            public double globalModifier = 0.5;
+
+            @Config.Comment("Modifier for how quickly devices (i.e. charcoal forge, fire pit) gain and lose heat. Smaller number = slower temperature changes.")
```
Comment (Claycorp) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]:
```suggestion
            @Config.Comment("Modifier for how quickly devices (i.e. charcoal forge, fire pit) will gain or lose heat. Smaller number = slower temperature changes.")
```

**Review by Claycorp — COMMENTED** [review]
Just a bunch of random changes. Seems good enough otherwise for the rest of 1.12

File: src/main/java/net/dries007/tfc/ConfigTFC.java (hunk 8 above)
Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/ConfigTFC.java]: You mean this?
```java
            @Config.Comment("Chance that leaves will drop more sticks when harvested with configured tool classes.")
            @Config.RangeDouble(min = 0, max = 1)
            @Config.LangKey("config." + MOD_ID + ".general.tree.leafStickDropChanceBonus")
            public double leafStickDropChanceBonus = 0.25;

            @Config.Comment("Tool classes that have the configured bonus to drop more sticks when harvesting leaves.")
            @Config.LangKey("config." + MOD_ID + ".general.tree.leafStickDropChanceBonusClasses")
            public String[] leafStickDropChanceBonusClasses = new String[] {"knife", "scythe"};
```

File: src/main/java/net/dries007/tfc/ConfigTFC.java (hunk 10 above)
Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/ConfigTFC.java:266]: What do you mean? I don't think we should add a a `/CT mainhand` like command for something like `DamageSource`, same thing for `Entity` entries, they are all Registry entries that already are in forge and vanilla, and other utility mods can dump them if a pack maker so requires.

File: src/main/java/net/dries007/tfc/ConfigTFC.java (hunk 27 above)
Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/ConfigTFC.java:408]: This falls in the same category as the changes you requested for damages:
- **How to get entity ID?** Use utility mods, it's not a secret that only TFC know.
- **What conditions does respawn use?** Exactly the same as vanilla: randomly selected from the list of creatures.

File: src/main/java/net/dries007/tfc/ConfigTFC.java (hunk 32 above)
Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/ConfigTFC.java:544]: Same as the others, use utility mods.

File: src/main/java/net/dries007/tfc/ConfigTFC.java (hunk 33 above)
Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/ConfigTFC.java:548]: Same as the others, use utility mods.

File: src/main/java/net/dries007/tfc/ConfigTFC.java (hunk 36 above)
Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/ConfigTFC.java:552]: Same as the others, use utility mods.

File: src/main/java/net/dries007/tfc/ConfigTFC.java (hunk 37 above)
Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/ConfigTFC.java:556]: Same as the others, use utility mods.

File: src/main/java/net/dries007/tfc/ConfigTFC.java (hunk 39 above)
Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/ConfigTFC.java:706]: Same as the others, use utility mods.
