### PR TITLE
Extinction of simple issues

### LINKED ISSUE #588: Charcoal pit should be added to JEI for charcoal.
Currently there is no mention of charcoal pits in JEI. Would be a good idea to add a fake recipe thing or some info about them.

### LINKED ISSUE #792: Metal trapdoors are missing.
A person or two has asked about the return of TFC metal trapdoors.

Currently we don't have anything other than vanilla ones.

### LINKED ISSUE #931: Separate rock/sample/stick "debris" spawn rate configs.
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Currently rocks, samples and sticks are all considered the same thing when toggling their spawning/regeneration in the config, this means I can't disable the generation of rocks/sticks without disabling surface samples. Or any combination of the three.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
Ability to disable/change rarity/regeneration of sticks, rocks and surface samples separate from one-another.

**Meta Info**
 - TFC Version: 1.12.2-0.30.3.124 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Both.

### LINKED ISSUE #956: Jug filling should have a dedicated sound event instead of reusing the water bucket filling sound event
Currently it just uses the exact same sound event as filling a bucket, leading to an incorrect subtitle being displayed (as was reported in that old TFC-Assets issue):

### LINKED ISSUE #967: A way to obtain ice
Having it drop when no blocks are adjacent to it like with stone would probably work. Water would be considered an adjacent block.

### LINKED ISSUE #1090: Missing Unfired Crucible
**Describe the request**

Currently, crucibles are crafted directly, rather than fired from an unfired item like all the other clay and fire clay items. There should be an unfired crucible which needs to be fired in a kiln.

**Meta Info**
 - TFC Version: 1.0.6.133

### LINKED ISSUE #1091: Broken glass item from breaking glass.
TFC 133
TFC Glass is sorta expensive, Adding a chance for shards to drop or making glass piles crafted from shards to be remelted would be a good addition to glass. Yes lots of mods do this, but I think we can add it.

### LINKED ISSUE #1113: Particles for misc things.
133 TFC
Fire related things can use some fun magic particles of fire and things.
Leaves could get some particles added of leaves falling.
Grill cooking food effect.
Anvil smithing effects on hit.
add sluice splash effects.

### LINKED ISSUE #1115: Add a way to remove/change out pot/grill on firepit.
TFC 133
Title.

### LINKED ISSUE #1241: Glass as a valid block for charcoal pits
This would give a good way to know when the charcoal is ready and i would say glass should be able to withstand the temperatures posed by charcoal making, since bricks also do.
**Meta Info**
 - TFC Version: 1.0.12.141(at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
 - If necessary, what other mods (including versions) would this require?

### LINKED ISSUE #1358: Different crops should require different temp/railfall to grow (like fruit trees)
At the moment crops all have the same requirements when it comes to temp/rainfall to grow besides bell peppers, jute and sugarcane, imo it should be different for each crop, like it is for fruit trees.
I also recomend that crops and fruit trees only spawn where the environment is suitable

**Meta Info**
 - TFC Version: 0.X.X.146 (at time of request)

### LINKED ISSUE #1376: Flux doesn't show on anvil.
Fluxes aren't displayed on top of the anvil like hammer.
Version: 147.

### LINKED ISSUE #1399: Config to disable farmland creation.
A config to disable the creation of farmland (equivalent to the existing config to disable path creation) would be incredibly useful.

### LINKED ISSUE #1403: Charcoal from sticks
1. What problem or issue would this enhancement solve?
ridiculous amounts of sticks pile up in a wood farm. Those can only be left to despawn at some point, since torches and ladders are not in as high demand as charcoal and wood for building. 
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
I suggest sticks can be placed in log piles - 16 or 64 per slot. Those log piles can be turned into charcoal just like any other log pile depending how full they are.

**Meta Info**
 - TFC Version: 1.4.0.149 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
no
 - If necessary, what other mods (including versions) would this require?
none

### LINKED ISSUE #1411: Add config option for acceptable anvil range.
We talked about this in the past, Currently the anvil requires a pixel perfect meeting of the arrows. Adding a config that adds a buffer of X+- to it would be appreciated by users.

Also talked about was the option of making the skill allow a closer option be valid. Though this might get tossed in 1.15, could possible look at effecting the bonus applied too.

### LINKED ISSUE #1435: Dyed alabaster bricks can be dyed the same color multiple times
Dyed alabaster bricks can be dyed the same color multiple times, which ends up using all of the dye in the barrel
I assume the same problem happens with all the items that can be dyed.

**Meta Info**
 - TFC Version: 0.X.X.152
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

### LINKED ISSUE #1459: Ceramic pots should show their content
Ceramic pots placed on campfires should show their contents, so players can know without constantly opening the GUI, what's the current state of cooking, whether it's empty, needs ingredients or if soup is ready.

### LINKED ISSUE #1494: Allow barrels to reflect day/week/month/year time frames for item processing.
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Display easier to read time frames for recipes added via other mods, CraftTweaker, and so on...
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
Rather than seeing a silly display of "This takes 1464 hours to process", we would see "this takes 5 months and X days to process" or 61 days in TFC time. Or whatever the actual time frame would be...

### LINKED ISSUE #1510: The torches can float around the sluice
**Describe the bug**
The torches placed around the sluice can float in the air. 
A9A38FEB-B66F-4EE6-B188-13D30DA8D1CA

**Meta Info**
 - TFC Version: 1.6.0.156

### LINKED ISSUE #1519: Add lumber crafting recipe for trapdoors
Just a small request.
The current crafting recipe for wooden trapdoors has the same vanilla crafting recipe that uses plank blocks.
Although the recipe yields 4 trapdoors instead of the vanilla 2, wooden doors can be crafted out of plain lumber and also yield 2 per recipe, meaning you can get more doors per log compared to trapdoors. 
To make trapdoors consistent with doors, they could be given the following recipe:
[https://cdn.discordapp.com/attachments/448709615702769666/740421351436714064/unknown.png](url)
Since trapdoors are also half the size of doors, this recipe could logically even yield a total of 4 trapdoors since it is the same amount of lumber used to create 2 doors. However, I can see that that may be an excessive amount gameplay-wise, so the yield could be lowered. 
Regardless of yield, I just think it would be nice for the trapdoors to have a lumber recipe for consistency.

Thanks!

### LINKED ISSUE #1522: New trapdoors visual bug
Trapdoors dont match textures correctly when opened.

This 2 screenshots can show that.

java_h82f9A7u6Y
java_AAAa1wF42N

Version: MC1.12.2-1.6.1.157

### LINKED ISSUE #1530: Wrong pixel on Red Steel Shield model
When i holding shield i see in third person that Red Steel Shield has a blinking pink pixel on one side of model

Screenshots:

ApplicationFrameHost_ajOCjh1WXo

ApplicationFrameHost_CnQ0bSjyFy

Version: MC1.12.2-1.6.1.157

### LINKED ISSUE #1531: Punching a lamp should not destroy it.
Breaking a lamp with bare hands should still yield a lamp.

Make sure to include:
1. What did you expect to happen? Break lamp and receive lamp in inventory
2. What actually happened instead (i.e. what was the bug): Break lamp with bare hand and you get no lamp

**To Reproduce**
Attention to detail is important!
1. Do '...' Place lamp.
2. Then do 'punch lamp with bare hand'
3. Receive no lamp back.

**Meta Info**
 - TFC Version: .TerraFirmaCraft MC1.12.2-1.6.1.157
 - Were any other mods included? No
 - If necessary, what other mods (including versions) MUST be present to experience the bug? None

### LINKED ISSUE #1532: "Navite" English typo in find native gold + silver advancements
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Expected "Native Gold" and "Native Silver" to be spelled correctly
2. What actually happened instead (i.e. what was the bug)
It is spelled "Navite Gold" + "Navite Silver"
3. If it was a crash, upload the full log file (`latest.log`)
N/A
4. If they would help to explain the issue, include screenshots
Not necessary

**To Reproduce**
Attention to detail is important!
1. Look at TerraFirmaCraft World advancements tab
2. Gold Rush and Silver Bullet advancements say "Navite Gold" and "Navite Silver" respectively

**Meta Info**
 - TFC Version: 1.6.1.157
 - Were any other mods included? Can you reproduce it without these other mods?  other mods were included but this can be reproduced without other mods
 - If necessary, what other mods (including versions) MUST be present to experience the bug?  N/A

### LINKED ISSUE #1535: Impossible to create stone anvil if place tool rack above stone block.
**Describe the bug**
Make sure to include:
1. What did you expect to happen? - Successful creation of a stone anvil
2. What actually happened instead (i.e. what was the bug) - I cant create stone anvil with hammer, if tool rack above the stone block, in 1.7.10 you can do this without problems

**To Reproduce**
1. Place valid for anvils stone block on the ground
2. Place tool rack above stone block
3. Try to create stone anvil by right clicking with hammer on stone block.

**Meta Info**
 - TFC Version: MC1.12.2-1.6.1.157

This maybe a minor issue, but for people who moved from 1.7.10 to 1.12.2 TNG it can be confusing.

### LINKED ISSUE #1540: Missing soundevent localization entries
Mentioned in #1521.

### LINKED ISSUE #1541: Patchouli book causes crash
There are 2 things about it. One is that bear is renamed, so previous "bear"s in `predarors` should be renamed too. The other one is that opening `steel` section causes crash. Here is the crash report.

[crash-2020-08-26_10.16.45-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5127189/crash-2020-08-26_10.16.45-client.txt)

EDIT: It has nothing to do with `steel` section, sry.

### PR DESCRIPTION
**Pull request by eerussianguy**
Seatbelts, everyone.

Crop Changes:
- Wild Crops now spawn more mature based on the season, becoming mature around Late Summer
- Closes #1358 Crops now have different temperature and rainfall requirements to spawn and grow at different speeds
- These are enumerated on the spreadsheet, but to summarize:
- Maize, Rice, and Sugarcane prefer the hottest temperatures.
- Beets, Cabbage, Garlic, and Barley prefer colder temperatures. Garlic can survive up to -20 C.
- Some crops favor a wide range of temperature and rainfall, some are rather picky

Closes #1403 Added uses for Sticks:
- Burning a Bunch of Sticks produces 18 torches
- Armor stands can be crafted using a bunch of sticks and a smooth slab
- Crafting two bunches of sticks together vertically produces a Stick Bundle
- A Stick Bundle is for all intents and purposes a kind of log, except that it cannot be placed normally.
- Stick Bundles are a slightly below average fuel for Firepits
- Stick Bundles can be stored in Log Piles and therefore used to create Charcoal Pits

Closes #1435 changed how dyeing Alabaster and other blocks works
- The only blocks that are able to be barrel-dyed are the 'natural' states of each block, i.e. White Wool for Wool or Aggregate for Concrete Powder
- Blocks can be bleached into their natural form using the new liquid Lye, at a ratio of 125mB per block in a Barrel.
- Lye is made from 125 mB of Wood Ash (dropped by Firepits) in Spring Water

Closes #1091 Breaking glass has a 50% chance to drop Glass Shards, which can be melted back into Glass.

Firepit Changes:
- Changed model for the Firepit and the Ceramic Pot
- Firepit will make a sound when it's boiling or grilling
- Food on the grill will now show up in the world
- Closes #1115 Shift + Right-Click when the grill is empty to remove the attachment
- Added custom damage sources for attempting to remove a hot attachment from the Firepit
- Closes #1459 Ceramic Pots render water inside, which changes color to a reddish brown when finished cooking.
- Breaking a Firepit drops Wood Ash, used to make Lye.

Closes #1113 Added new particle effects:
- 3 new leaf particles, that drop when a leaf expires and float away.
- Bubbles from boiling soup
- Smoke from Grilling
- Sparks when welding an item on the anvil
- Firepit smoke has been split into 3 new particles, which look less like burning tires and more like smoke
- Decreased the overall speed of smoke rising
- Forges shoot out bits of lava and smoke randomly

Misc:
Closes #1535 Stone Anvils can be created if under any non-solid block (i.e. tool racks)
Closes #1519 Trapdoors are now crafted with 6 lumber to make 3 trapdoors
Closes #1494 Barrels will now show the recipe length in days if appropriate
Closes #1411 Anvils have a config for an "acceptable range" around the target where the smithing recipe will finish (default 0)
Closes #1399 Config to disable TFC hoes creating farmland
Closes #1376 Flux now shows on the anvil
Closes #1241 Glass is now a valid block for Charcoal Pits (can be disabled through config)
Closes #1090 Knapping a Crucible now produces an Unfired Crucible, which has to be cooked.
Closes #967 Breaking Ice with a Saw will drop the Ice block.
Closes #956 Jug filling has it's own sound event and custom sound.
Closes #931 Debris types (rocks, sticks, ores) can be disabled individually through config
Closes #792 Added Metal Trapdoors, which are smithed from Sheets.
Closes #588 Charcoal Pit explainer now appears in JEI when you click Charcoal

Fixes:
Closes #1541 Patchouli crash due to changed entity names
Closes #1540 Missing sound event localization
Closes #1532 Incorrect advancement localization
Closes #1530 bad model data for red steel shield
Closes #1531 Can't break lamp with hand (changed material to REDSTONE_LIGHT)
Closes #1522 Trapdoors rendered wrong
Closes #1510 Sluices allow placing torches on top

### CODE REVIEW

File: src/main/java/net/dries007/tfc/objects/items/ItemStickBundle.java [hunk 1]
```diff
@@ -0,0 +1,33 @@
+package net.dries007.tfc.objects.items;
+
+import net.dries007.tfc.api.capability.size.Size;
+import net.dries007.tfc.api.capability.size.Weight;
+import net.dries007.tfc.util.OreDictionaryHelper;
+import net.minecraft.item.ItemStack;
+
+import javax.annotation.Nonnull;
+
+public class ItemStickBundle extends ItemTFC
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/items/ItemStickBundle.java]: This class is redundant. Just use `ItemMisc` and pass in the correct size / ore dictionary names. Mind the required format (e.g. `log_wood`, `stick_bundle`). See other examples for usage.

File: src/main/java/net/dries007/tfc/objects/blocks/devices/BlockFirePit.java [hunk 2]
```diff
@@ -273,6 +320,46 @@ else if (tile.getCookingPotStage() == TEFirePit.CookingPotStage.FINISHED)
...
+                    else
+                    {
+                        tile.onRemoveAttachment();
+                        worldIn.setBlockState(pos, state.withProperty(ATTACHMENT, FirePitAttachment.NONE));
+                        ItemStack attachmentItem = ItemStack.EMPTY;
+                        if (attachment == FirePitAttachment.COOKING_POT)
+                            attachmentItem = ItemsTFC.FIRED_POT.getDefaultInstance();
+                        if (attachment == FirePitAttachment.GRILL)
+                            attachmentItem = ItemsTFC.WROUGHT_IRON_GRILL.getDefaultInstance();
+                        player.addItemStackToInventory(attachmentItem);
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/blocks/devices/BlockFirePit.java]: No, this needs to give the actual item instance back to the player that is held by the tile. That's *why it is held there*.

File: src/main/java/net/dries007/tfc/objects/te/TEFirePit.java [hunk 3]
```diff
@@ -581,6 +583,11 @@ public void onConvertToGrill(EntityPlayer player, ItemStack stack)
         attachedItemStack = stack.splitStack(1);
     }
 
+    public void onRemoveAttachment()
+    {
+        attachedItemStack = ItemStack.EMPTY;
+    }
+
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/te/TEFirePit.java]: No, this should handle dropping and giving back to player, as the attachedItemStack needs to be given back to the player exactly.

**Review by alcatrazEscapee — CHANGES_REQUESTED** [review]

File: src/main/java/net/dries007/tfc/objects/blocks/devices/BlockFirePit.java (hunk 2 above)
Comment (alcatrazEscapee) [reply src/main/java/net/dries007/tfc/objects/blocks/devices/BlockFirePit.java]: Also, you CANNOT call `Item#getDefaultInstance` here as it is `@SideOnly(Side.CLIENT)`, which will crash and burn on dedicated servers.

File: src/main/resources/assets/tfc/lang/en_us.lang [hunk 4]
```diff
@@ -4764,8 +4819,14 @@ tfc.animal.boar.cry=Boar cries
 tfc.animal.boar.hurt=Boar hurts
 tfc.animal.boar.death=Boar dies
 tfc.animal.wildebeest.say=Wildebeest grunts
+tfc.animal.wildebeest.hurt=Wildebeest hurts
+tfc.animal.wildebeest.death=Wildebeest dies
 tfc.animal.quail.say=Quail chirps
+tfc.animal.quail.hurt=Quail hurts
+tfc.animal.quail.death=Qual dies
```
Comment (HeartyYF) [inline src/main/resources/assets/tfc/lang/en_us.lang]: `Quail`

File: src/main/resources/assets/tfc/patchouli_books/book/en_us/entries/food/animal_husbandry.json [hunk 5]
```diff
@@ -23,13 +23,13 @@
...
 			"type": "text",
-			"text": "Some livestock are able to produce different products when they are familiarized and an adult. Cows and goats produce milk (right-click with a bucket to retrieve), while sheep and alpacas will allow you to shear them."
+			"text": "Some livestock are able to produce different products when they are familiarized and an adult. Cows, Zebus, Yaks, and goats produce milk (right-click with a bucket to retrieve), while sheep and alpacas will allow you to shear them."
 		},
 		{
 			"type": "crafting",
 			"recipe": "tfc:nest_box",
 			"title": "Nest Box",
-			"text": "Chickens lay eggs daily if you give them a $(item)nest box$() to use. As long as a rooster is near the nest box when the egg is laid, the egg will become fertilized and will hatch eventually. Eggs can also be cooked for food."
+			"text": "Chickens, Grouses, and Quails lay eggs daily if you give them a $(item)nest box$() to use. As long as a rooster is near the nest box when the egg is laid, the egg will become fertilized and will hatch eventually. Eggs can also be cooked for food."
```
Comment (HeartyYF) [inline src/main/resources/assets/tfc/patchouli_books/book/en_us/entries/food/animal_husbandry.json]: I suggest mentioning ducks

File: src/main/resources/assets/tfc/patchouli_books/book/en_us/entries/getting_started/predators.json [hunk 6]
```diff
@@ -50,6 +50,48 @@
...
+    {
+      "type": "entity",
+      "name": "Cougar",
+      "text": "The Cougar hunts during the night.",
+      "entity": "tfc:cougartfc",
+      "scale": 0.7
+    },
+    {
+      "type": "entity",
+      "name": "Panther",
```
Comment (HeartyYF) [inline src/main/resources/assets/tfc/patchouli_books/book/en_us/entries/getting_started/predators.json]: Another panther. Maybe it should be something else, but seems only 5 predators were added.

File: src/main/resources/assets/tfc/patchouli_books/book/en_us/entries/getting_started/predators.json [hunk 7]
```diff
@@ -50,6 +50,48 @@
...
+      "text": "The Panther hunts during the night.",
+      "entity": "tfc:panthertfc",
+      "scale": 0.7
+    },
+    {
+      "type": "entity",
+      "name": "Panther",
```
Comment (HeartyYF) [inline src/main/resources/assets/tfc/patchouli_books/book/en_us/entries/getting_started/predators.json]: The third panther.

**Review by HeartyYF — CHANGES_REQUESTED** [review]

File: src/main/resources/assets/tfc/patchouli_books/book/en_us/entries/food/animal_husbandry.json [hunk 8]
```diff
@@ -29,7 +29,7 @@
 			"type": "crafting",
 			"recipe": "tfc:nest_box",
 			"title": "Nest Box",
-			"text": "Chickens, Grouses, and Quails lay eggs daily if you give them a $(item)nest box$() to use. As long as a rooster is near the nest box when the egg is laid, the egg will become fertilized and will hatch eventually. Eggs can also be cooked for food."
+			"text": "Chickens, Grouses, Ducks, and Quails lay eggs daily if you give them a $(item)nest box$() to use. As long as a rooster is near the nest box when the egg is laid, the egg will become fertilized and will hatch eventually. Eggs can also be cooked for food."
```
Comment (DisasterMoo) [inline src/main/resources/assets/tfc/patchouli_books/book/en_us/entries/food/animal_husbandry.json]:
```suggestion
			"text": "Chickens, Grouses, Ducks, and Quails lay eggs daily if you give them a $(item)nest box$() to use. As long as a male from the same species mate with the female before she lay eggs, the egg will become fertilized and will hatch eventually. Eggs can also be cooked for food."
```

**Review by DisasterMoo — CHANGES_REQUESTED** [review]

File: src/main/java/net/dries007/tfc/objects/te/TEAnvilTFC.java [hunk 9]
```diff
@@ -240,7 +241,9 @@ public void addStep(@Nonnull EntityPlayer player, @Nullable ForgeStep step)
             if (recipe != null)
             {
                 AnvilRecipe completedRecipe = recipe; // Hold the current recipe, as setting the input slot to empty will clear it
-                if (workingProgress == workingTarget && completedRecipe.matches(steps))
+                int workMin = workingTarget - ConfigTFC.General.DIFFICULTY.acceptableAnvilRange;
+                int workMax = workingTarget + ConfigTFC.General.DIFFICULTY.acceptableAnvilRange;
+                if ((workingProgress < workMax && workingProgress > workMin) && completedRecipe.matches(steps))
```
Comment (DisasterMoo) [inline src/main/java/net/dries007/tfc/objects/te/TEAnvilTFC.java]:
```suggestion
                if ((workingProgress <= workMax && workingProgress >= workMin) && completedRecipe.matches(steps))
```
otherwise, this will make it impossible to finish if both `workMin` and `workMax` are the same (default config = 0)

**Review by DisasterMoo — CHANGES_REQUESTED** [review]

**Review by DisasterMoo — APPROVED** [review]
