### PR TITLE
Dye, Colored blocks and many fixes.

### LINKED ISSUE #891: The Flower pot should have a knapping and Kiln Recipe
The Vanilla Recipe should follow the production chain of other ceramics items.
Kanpped from clay Fired in the Pit Kiln

### PR DESCRIPTION
**Pull request by Claycorp**
Don't question code binges. It's a bit of a mix but it all should work well.

Main focus was new Dye system and implementing it correctly, All supporting recipes should be there.
Secondary was clearing as many simple issues off the issue list and a few direct from players.

Rip it up fam. (I think I did this all right?)

Fixes #891

### CODE REVIEW

File: src/main/java/net/dries007/tfc/CommonEventHandler.java [hunk 1]
```diff
@@ -685,7 +685,8 @@ public static void onFluidPlaceBlock(BlockEvent.FluidPlaceBlockEvent event)
         {
             event.setNewState(BlockRockVariant.get(Rock.BASALT, Rock.Type.RAW).getDefaultState().withProperty(BlockRockRaw.CAN_FALL, false));
         }
-        if (event.getNewState().getBlock() == Blocks.COBBLESTONE)
+
+        if (!ConfigTFC.GENERAL.disableCobbleGenOverride && event.getNewState().getBlock() == Blocks.COBBLESTONE)
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/CommonEventHandler.java]: This is already fixed in the current 1.12.x branch, and I believe this is showing up as a conflict. For reference it's fixed [here](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/60a058d27865be5f3535c89438e5c209ec44b3d7/src/main/java/net/dries007/tfc/CommonEventHandler.java#L681)

File: src/main/java/net/dries007/tfc/ConfigTFC.java [hunk 2]
```diff
@@ -55,6 +55,21 @@ public static void onConfigChangedEvent(ConfigChangedEvent.OnConfigChangedEvent
         @Config.LangKey("config." + MOD_ID + ".general.disableFallableBlocks")
         public boolean disableFallableBlocks = false;
 
+        @Config.Comment({"Disable the override TFC does when lava and water meet.",
+            "Only use if you want vanilla cobblestone or have another mod that changes this."})
+        @Config.LangKey("config." + MOD_ID + ".general.disableCobbleGenOverride")
+        public boolean disableCobbleGenOverride = false;
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/ConfigTFC.java]: Same as previous, this is already fixed and this would be duplicating a config option.

File: src/main/java/net/dries007/tfc/api/capability/heat/CapabilityItemHeat.java [hunk 3]
```diff
@@ -39,6 +40,7 @@ public static void preInit()
         CapabilityManager.INSTANCE.register(IItemHeat.class, new DumbStorage<>(), ItemHeatHandler::new);
         //register heat on vanilla egg for cooking
         CapabilityItemHeat.CUSTOM_ITEMS.put(IIngredient.of(Items.EGG), () -> new ItemHeatHandler(null, 1, 480));
+        CapabilityItemHeat.CUSTOM_ITEMS.put(IIngredient.of(ItemsTFC.UNFIRED_BRICK), () -> new ItemHeatHandler(null, 1, 1601));
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/api/capability/heat/CapabilityItemHeat.java]: I don't believe this is used anymore since the unfired brick uses `ItemPottery`?

File: src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java [hunk 4]
```diff
@@ -56,6 +60,114 @@
     @GameRegistry.ObjectHolder("ceramics/fired/large_vessel")
     public static final BlockLargeVessel FIRED_LARGE_VESSEL = getNull();
 
+    @GameRegistry.ObjectHolder("aggregate")
+    public static final BlockGravel AGGREGATE = getNull();
+
+    @GameRegistry.ObjectHolder("alabaster/bricks/white")
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java]: This is not the example of what's been done in other places in TFC, but I think it's both the best solution for this particular case, and what's most like the `RegistryObject` map based stuff I think we should move to in 1.15. So instead:
```java
public static final Map<EnumDyeColor, BlockDecorativeStone> ALABASTER_BRICKS = new HashMap<>();
public static final Map<EnumDyeColor, BlockDecorativeStone> ALABASTER_POLISHED = new HashMap<>();
public static final Map<EnumDyeColor, BlockDecorativeStone> ALABASTER_RAW = new HashMap<>();
```

File: src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java [hunk 5]
```diff
@@ -115,6 +227,10 @@
 
     private static ImmutableList<BlockBerryBush> allBerryBushBlocks;
 
+    private static ImmutableList<ItemBlock> allAlabasterRawBlocks;
+    private static ImmutableList<ItemBlock> allAlabasterBricksBlocks;
+    private static ImmutableList<ItemBlock> allAlabasterPolishedBlocks;
+
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java]: These shouldn't be necessary, the item blocks are all simple items and can have their model registration bundled with everything else.
```suggestion
```

File: src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java [hunk 6]
```diff
@@ -266,6 +382,21 @@
...
+    public static ImmutableList<ItemBlock> getAllAlabasterBricksBlocks()
+    {
+        return allAlabasterBricksBlocks;
+    }
+
+    public static ImmutableList<ItemBlock> getAllAlabasterPolishedBlocks()
+    {
+        return allAlabasterPolishedBlocks;
+    }
+
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java]:
```suggestion
```

File: src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java [hunk 7]
```diff
@@ -297,6 +431,37 @@ public static void registerBlocks(RegistryEvent.Register<Block> event)
         normalItemBlocks.add(new ItemBlockTFC(register(r, "sea_ice", new BlockIceTFC(FluidsTFC.SALT_WATER.get()), CT_MISC)));
 
         normalItemBlocks.add(new ItemBlockLargeVessel(register(r, "ceramics/fired/large_vessel", new BlockLargeVessel(), CT_POTTERY)));
+        {
+            Builder<ItemBlock> raw = ImmutableList.builder();
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java]: There's no need for the separate builders here. All the registration calls can be be adjusted to add the block to the respective map:
```java
// Inside each EnumDyeColor loop
BlockDecorativeStone block = new BlockDecorativeStone( ... );
normalItemBlocks.add(new ItemBlockTFC(register(r, "alabaster/whatever" + dyeColor.getName(), block)));
ALABASTER_RAW.put(color, block);
```

File: src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java [hunk 8]
```diff
@@ -297,6 +431,37 @@ public static void registerBlocks(RegistryEvent.Register<Block> event)
...
+            Builder<ItemBlock> polished = ImmutableList.builder();
+            Builder<ItemBlock> bricks = ImmutableList.builder();
+
+            raw.add(new ItemBlockTFC(register(r, "alabaster/raw/plain", new BlockDecorativeStone(MapColor.SNOW), CT_DECORATIONS)));
+            for (EnumDyeColor dyeColor : EnumDyeColor.values())
+            {
+                raw.add(new ItemBlockTFC(register(r, "alabaster/raw/" + dyeColor.getDyeColorName(), new BlockDecorativeStone(MapColor.getBlockColor(dyeColor)), CT_DECORATIONS)));
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java]: `EnumDyeColor#getDyeColorName` is annotated as `SideOnly(Side.CLIENT)`. Use `getName` instead, as it returns the same field.

File: src/main/java/net/dries007/tfc/objects/fluids/FluidsTFC.java [hunk 9]
```diff
@@ -64,6 +64,23 @@
     public static FluidWrapper WHISKEY;
     public static FluidWrapper BEER;
     public static FluidWrapper RUM;
+    // Dye
+    public static FluidWrapper BLACK_DYE;
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/fluids/FluidsTFC.java]: Instead of this, we should mimic metal fluids, with a `Map<EnumDyeColor, FluidWrapper>`. I'm not concerned with making everything immutable as imo it makes more ugly code than it helps.

```java
// Storage
private static Map<EnumDyeColor, FluidWrapper> DYE;

public static FluidWrapper getFluidFromDye(EnumDyeColor color) { ... }
```

File: src/main/java/net/dries007/tfc/objects/fluids/FluidsTFC.java [hunk 10]
```diff
@@ -162,7 +179,24 @@ public static void registerFluids()
...
+                PINK_DYE = registerFluid(new Fluid("pink_dye", STILL, FLOW, 0xFFF38BAA)),
+                GRAY_DYE = registerFluid(new Fluid("gray_dye", STILL, FLOW, 0xFF474F52)),
+                LIGHT_GRAY_DYE = registerFluid(new Fluid("light_gray_dye", STILL, FLOW, 0xFF9D9D97)),
+                CYAN_DYE = registerFluid(new Fluid("cyan_dye", STILL, FLOW, 0xFF169C9C)),
+                PURPLE_DYE = registerFluid(new Fluid("purple_dye", STILL, FLOW, 0xFF8932B8)),
+                BLUE_DYE = registerFluid(new Fluid("blue_dye", STILL, FLOW, 0xFF3C44AA)),
+                BROWN_DYE = registerFluid(new Fluid("brown_dye", STILL, FLOW, 0xFF835432)),
+                GREEN_DYE = registerFluid(new Fluid("green_dye", STILL, FLOW, 0xFF5E7C16)),
+                RED_DYE = registerFluid(new Fluid("red_dye", STILL, FLOW, 0xFFB02E26)),
+                BLACK_DYE = registerFluid(new Fluid("black_dye", STILL, FLOW, 0xFF1D1D21))
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/fluids/FluidsTFC.java]: This can be replaced with a single map constructor.
 - One niche thing is that `EnumDyeColor#getColorValue` is client only, but `getColorComponentValues` is not. I think we can solve this via `new Color(f, g, b).getRGB()`

```java
DYE_FLUIDS = Arrays.stream(EnumDyeColor.values()).collect(Collectors.toMap(
    color -> color,
    color -> {
        float[] c = color.getColorComponentValues();
        return registerFluid(new Fluid(color.getName() + "_dye", STILL, FLOW, new Color(c[0], c[1], c[2]).getRGB()));
));
```

File: src/main/java/net/dries007/tfc/objects/items/metal/ItemIngot.java [hunk 11]
```diff
@@ -84,7 +85,7 @@ public EnumActionResult onItemUse(EntityPlayer player, World worldIn, BlockPos p
                             return EnumActionResult.SUCCESS;
                         }
                     }
-                    else if (stateTop.getBlock().isReplaceable(worldIn, posTop) && worldIn.mayPlace(BlocksTFC.INGOT_PILE, posTop, false, EnumFacing.UP, null))
+                    else if (stateTop.getBlock().isReplaceable(worldIn, posTop) && worldIn.mayPlace(BlocksTFC.INGOT_PILE, posTop, false, EnumFacing.UP, null) && worldIn.getBlockState(posTop).getBlock().getBlockFaceShape(worldIn, worldIn.getBlockState(posTop), posTop, EnumFacing.UP) == BlockFaceShape.SOLID)
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/objects/items/metal/ItemIngot.java]:
```suggestion
                    else if (stateTop.getBlock().isReplaceable(worldIn, posTop) && worldIn.mayPlace(BlocksTFC.INGOT_PILE, posTop, false, EnumFacing.UP, null) && stateTop.getBlockFaceShape(worldIn, posTop, EnumFacing.UP) == BlockFaceShape.SOLID)
```

File: src/main/java/net/dries007/tfc/types/DefaultRecipes.java [hunk 12]
```diff
@@ -134,10 +138,168 @@ public static void onRegisterBarrelRecipeEvent(RegistryEvent.Register<BarrelReci
...
             //  previous todo had "make it a simpler calculation"
             new BarrelRecipe(IIngredient.of(FRESH_WATER.get(), 500), IIngredient.of("dustFlux"), new FluidStack(LIMEWATER.get(), 500), ItemStack.EMPTY, 0).setRegistryName("limewater"),
+            new BarrelRecipe(IIngredient.of(LIMEWATER.get(), 100), IIngredient.of(ItemsTFC.GYPSUM), null, new ItemStack(BlocksTFC.ALABASTER_RAW_PLAIN), ICalendar.TICKS_IN_HOUR).setRegistryName("plain_alabaster"),
 
             new BarrelRecipeTemperature(IIngredient.of(FRESH_WATER.get(), 1), 50).setRegistryName("fresh_water_cooling"),
             new BarrelRecipeTemperature(IIngredient.of(SALT_WATER.get(), 1), 50).setRegistryName("salt_water_cooling")
         );
+
+        //Nice handy list of dye in the correct order BY META DATA to get the correct fluid.
+        List<FluidWrapper> fluids = new ArrayList<>();
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/types/DefaultRecipes.java]: No please. If the fluids are stored via `Map<EnumDyeColor, FluidWrapper>`, the meta data can be retrieved automatically via `EnumDyeColor#getMetadata()`

i.e. `fluids.get(dyeMeta).get()` gets replaced wth `FluidsTFC.DYE.get(color).get()`

File: src/main/java/net/dries007/tfc/types/DefaultRecipes.java [hunk 13]
```diff
@@ -134,10 +138,168 @@ public static void onRegisterBarrelRecipeEvent(RegistryEvent.Register<BarrelReci
...
+        fluids.add(BLUE_DYE);
+        fluids.add(BROWN_DYE);
+        fluids.add(GREEN_DYE);
+        fluids.add(RED_DYE);
+        fluids.add(BLACK_DYE);
+
+        //The many many many recipes that is dye. This assumes that the standard meta values for colored objects are followed.
+        for (EnumDyeColor dyeColor : EnumDyeColor.values())
+        {
+            String dyeName = dyeColor.getDyeColorName();
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/types/DefaultRecipes.java]: `EnumDyeColor#getDyeColorName` is client only, don't use.
```suggestion
            String dyeName = dyeColor.getName();
            if (dyeColor == EnumDyeColor.SILVER)
            {
                dyeName = "light_gray";
            }
```

File: src/main/java/net/dries007/tfc/types/DefaultRecipes.java [hunk 14]
```diff
@@ -134,10 +138,168 @@ public static void onRegisterBarrelRecipeEvent(RegistryEvent.Register<BarrelReci
...
+                    new BarrelRecipe(IIngredient.of(fluids.get(dyeMeta).get(), 125), IIngredient.of("wool"), null, new ItemStack(Blocks.WOOL, 1, dyeMeta), ICalendar.TICKS_IN_HOUR).setRegistryName("wool_" + dyeName),
+                    new BarrelRecipe(IIngredient.of(fluids.get(dyeMeta).get(), 25), IIngredient.of("carpet"), null, new ItemStack(Blocks.CARPET, 1, dyeMeta), ICalendar.TICKS_IN_HOUR).setRegistryName("carpet_" + dyeName),
+                    new BarrelRecipe(IIngredient.of(fluids.get(dyeMeta).get(), 125), IIngredient.of("bed"), null, new ItemStack(Blocks.BED, 1, dyeMeta), ICalendar.TICKS_IN_HOUR).setRegistryName("bed_" + dyeName),
+                    new BarrelRecipe(IIngredient.of(fluids.get(dyeMeta).get(), 125), IIngredient.of("powderConcrete"), null, new ItemStack(Blocks.CONCRETE_POWDER, 1, dyeMeta), ICalendar.TICKS_IN_HOUR).setRegistryName("concrete_" + dyeName),
+                    new BarrelRecipe(IIngredient.of(fluids.get(dyeMeta).get(), 125), IIngredient.of(BlocksTFC.AGGREGATE), null, new ItemStack(Blocks.CONCRETE_POWDER, 1, dyeMeta), ICalendar.TICKS_IN_HOUR).setRegistryName("aggregate_" + dyeName)
+                );
+            }
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/types/DefaultRecipes.java]: Don't need to duplicate all these recipe names, just change the dye name initially and call the registration the way.

File: src/main/java/net/dries007/tfc/types/DefaultRecipes.java [hunk 15]
```diff
@@ -134,10 +138,168 @@ public static void onRegisterBarrelRecipeEvent(RegistryEvent.Register<BarrelReci
...
+        }
+
+        event.getRegistry().registerAll(
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/types/DefaultRecipes.java]: This should be three lines in a for loop
```java
for (EnumDyeColor color : EnumDyeColor.values())
{
    event.getRegistry().registerAll(
        new BarrelRecipe(IIngredient.of(FluidsTFC.DYE.get(color).get(), 125), IIngredient.of("alabasterBricks"), null, new ItemStack(BlocksTFC.ALABASTER_BRICKS.get(color)), ICalendar.TICKS_IN_HOUR).setRegistryName("alabaster_bricks_" + color.getName()),
        // etc.
    );
}
```

**Review by alcatrazEscapee — CHANGES_REQUESTED** [review]
Initial feedback on where code cleanup could happen. Whack me if questions.

**Comment by Claycorp** [comment]
Also this fixed #891 Forgot to add that to the commits.
