### PR TITLE
Combat / Biomes / Animals

### LINKED ISSUE #621: Configurable damage-type weakness for mobs from other mods
**Describe the request**
Allowing the ability to allocate damage-type weakness to mobs from other mobs via. config would help a lot with integrating TFC:TNG with other mods. 

This could take the form of a config, similar to the already present "default damage type" lists, where you enter the entity name for the mob in question.

**Meta Info**
 - TFC Version: 0.27.2.101 (at time of request)
 - This is a compatibility feature, allowing better integration into modpacks.

### LINKED ISSUE #757: TFC swords don't have a sweep attack.
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Swords to have a sweeping attack, like most every vanilla or modded sword. (likely not part of ItemSword class.)
2. What actually happened instead (i.e. what was the bug)
No sweep attack.
From a user who posted in the Discord:
https://www.youtube.com/watch?v=aJydq0XNqTw

**To Reproduce**
Attack an entity, clearer when there are more of said entity next to it.

**Meta Info**
 - TFC Version: 1.12.2-0.28.1.111.

### LINKED ISSUE #758: Balancing the combat system
Let's take care of the current combat system
- [x] Tweak vanilla mobs damage resistance
- [x] Tweak animals damage resistance
- [x] Tweak animals health
- [x] Tweak damage output of weapons (attack speed + damage type + damage value)
- [x] Maybe move vanilla threats underground (if so, a buff would be welcome) and make animals the threat aboveground

### LINKED ISSUE #846: Yarr, There be no ink blasters in these waters!
Squids are missing.

Yeah... that's it.

Quit reading this, you already got what you came here for....

In case you forgot, there isn't any squids.

Ok bye.

### LINKED ISSUE #858: Newborn piglets are all hunchbacks
What was expected to happen: Baby pigs look like...small pigs
What actually happened: Baby pigs need to go to the chiropractor. They look like this:

It only happens on the newborn pigs though (1st stage of growth)

**To Reproduce**
1. Find or breed a baby pig
2. Look at the pig

**Meta Info**
 - TFC Version: 0.29.4.119
 - I had a few other addons installed. Pigs are still broken if I remove the other mods though.

### LINKED ISSUE #860: Animals can be fed rotten foods
Currently, farmable animals can be fed rotten foods for familiarity. 
Shouldn't that be prevented / cause negative effects (hurt + decrease familiarity)?

### LINKED ISSUE #948: Localization for deer male/female
**Meta Info**
 - TFC Version: 0.31.0.125

### LINKED ISSUE #976: old/young animal
I've seen it reported on discord, but do not think it was here. This should be the opposite.

tfc.tooltip.animal.product.old=This %s is too young.
tfc.tooltip.animal.product.young=This %s is too old.

### PR DESCRIPTION
**Pull request by DisasterMoo**
Created this draft so i can keep track of changes:
- Added Vanilla animals (Polar Bear, Ocelot/Cat, Parrot and Llama)
- Added Abdyman's animals (Black Panther, Goat, Duck and Alpaca)
- Fixed a bug in familiarity where children animals when become adult resets their familiarity to the cap.
- Added flora diversity & density to creature spawn mechanics.
- Added a helper class to figure out biome and tweaked world gen, should be creating savannas, tundras and plains (AKA areas where flora density is very low).
- Tweaked some animals to spawn on certain biomes.
- Added entity damage resistance capability loading via json (like Veins, Closes #621).
- Tweaked predators AI to be bound by time rules (ie: black panthers attack at night, bears at day, children never attacks. Rules are invalid [they will attack regardless] if animal is provoked).
- Metal swords now have the sweeping effect (Closes #757).
- Moved mobs to underground.
- Undead creatures now spawn with equipment.
- Mobs now have more resistance, should be more of a threat.
- Tweaked weapons/tools damage output.
- Fixed a bug in classic's old models (Closes #858)
- Some tweaks in animals: Some misc. animals hunt for food (ie: Untamed wolf hunts rabbits and sheep).
- Tweaked health and damage output of bears (the only predator *yet*)
- Added squids to aquatic biomes (Closes #846).
- Made a few changes to vanilla's respawning mechanic, should give more control over it.
- ~~Tripled~~ Doubled (was too much) mob spawn rate underground.
- Predators now don't implement `IMob` interface to not tamper with mob spawns underground (vanilla polar bears also don't, so i guess it's fine).
- Missing deer lang entries (Closes #948)
- Fixed animals eating rotten foods (Closes #860)
- Fixed switched old/young tooltips (Closes #976)

Closes #758

### CODE REVIEW

**Comment by alcatrazEscapee** [comment]
> Still WIP:
> Missing some predators.

I'm waiting on this right now as I'm working on other things, unless this is not actually work-in-progress and just work-that-should-be-done-but-not-planned.

**Comment by DisasterMoo** [comment]
It is WIP, but not by me. I'm waiting for the art guys (Therighthon, Abdyman) to finish their models and textures so i can finish their implementation / balance. Feel free to cherry pick the squid fix tho, since i guess people are asking for them lately.

File: src/main/java/net/dries007/tfc/world/classic/worldgen/vein/VeinRegistry.java [hunk 1]
```diff
@@ -9,7 +9,6 @@
 import java.io.IOException;
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/world/classic/worldgen/vein/VeinRegistry.java]: Currently, all of `config/tfc/` is reserved for ore veins, including subfolders, as it's scanned by `VeinRegistry`
Now keeping in mind all of this will be completely thrown out in 1.15, I still don't like this solution (restrict veins to top level folder, make damage resistance a subfolder). So instead, here's my proposal:
 - Move the tfc config parsing to a util class, `JsonConfigRegistry` which scans each file recursively in `config/tfc/`, and checks for a `#loader` field. Based on the value of this, either ask `VeinRegistry`, or `DamageResistanceRegistry` to handle the file. If the `#loader` field isn't present, use `VeinRegistry`.

Given the ability we have to choose the format of damage resistance entries, I think this is an acceptable solution for both keeping existing functionality and not too much effort / leaving this in a kludged up state. For instance, a damage entry would be as such:
```json
{
    "#loader": "tfc:damage_resistance",
    "minecraft:creeper": { "..." }
```

Then the changes you've made to both vein registration and parsing aren't nessecary.

File: src/main/java/net/dries007/tfc/world/classic/worldgen/vein/VeinRegistry.java [hunk 2]
```diff
@@ -107,31 +106,37 @@ public void postInit()
...
         {
-            recursivePathList = Files.walk(tfcConfigDir.toPath()).filter(Files::isRegularFile).toArray(Path[]::new);
+            allFiles = tfcConfigDir.listFiles();
+            Objects.requireNonNull(allFiles);
         }
-        catch (IOException e)
+        catch (NullPointerException e)
         {
-            TerraFirmaCraft.getLog().error("Unable to read files in the config directory! TFC will not generate any ore veins!");
+            TerraFirmaCraft.getLog().error("Unable to read files in the damage resistance directory! TFC will not set entities resistance data!");
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/world/classic/worldgen/vein/VeinRegistry.java]: copy-paste-typo

File: src/main/java/net/dries007/tfc/client/ClientEvents.java [hunk 3]
```diff
@@ -206,7 +216,6 @@ else if (mc.world.provider.getDimension() == 0)
                     data.getValidTrees().forEach(t -> list.add(String.format("%s %s (%.1f)", WHITE, t.getRegistryName(), t.getDominance())));
 
                     list.add(GRAY + "Sea level offset: " + WHITE + data.getSeaLevelOffset(x, z));
-                    list.add(GRAY + "Spawn Protection: " + WHITE + data.getSpawnProtection());
```
Comment (alcatrazEscapee) [inline src/main/java/net/dries007/tfc/client/ClientEvents.java]: Why? This is the only available location for this data atm.

File: src/main/resources/assets/tfc/config/entity_resistance_data.json [hunk 4]
```diff
@@ -0,0 +1,42 @@
+{
```
Comment (alcatrazEscapee) [inline src/main/resources/assets/tfc/config/entity_resistance_data.json:1]:
```suggestion
{
  "#loader": "tfc:damage_resistance"
```

**Review by alcatrazEscapee — CHANGES_REQUESTED** [review]
One concern with the entity json loader. It's a bit of a nitpick considering none of this is usable for 1.15 whatever we do, but I'd rather maintain existing functionality at the gripe of having a bit of a janky ass system.

As for the animals, I trust that you know what you're doing there and can either document or help as needed as far as wiki/questions are concerned.

File: src/main/java/net/dries007/tfc/world/classic/worldgen/vein/VeinRegistry.java (hunk 2 above)
Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/world/classic/worldgen/vein/VeinRegistry.java]: That error output is actually at the right location (`VeinRegistry`). The one that is in `DamageResistanceRegistry` is set correctly too

File: src/main/java/net/dries007/tfc/client/ClientEvents.java (hunk 3 above)
Comment (DisasterMoo) [reply src/main/java/net/dries007/tfc/client/ClientEvents.java]: Crud! I forgot to revert that! I removed at the earlier stages of development as we discussed that it would not be required after i moved mobs underground, but i decided to revert spawn protection since aggressive animals (predators) would still spawn at a player's base regardless of light sources, hence making this system much more needed

**Comment by DisasterMoo** [comment]
Done, I think the way it is now is good enough. I hope vanilla animals in 1.15 got code cleanup and be more mod friendly (use more protected variables instead of private --') so i can make more adjustments and less copy-paste.
